/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-07-03 12:12:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.qna;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qnaNew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>문의 게시판</title>\r\n");
      out.write("   <link href=\"/sp/css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("   <link href=\"/sp/vendor/bootstrap/css/bootstrap.min.css\"rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/sp/vendor/bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/sp/css/qnaNew.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"/sp/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<form class=\"fixed-top\" method=\"get\" action=\"\" style=\"padding: 20px 28px 20px 28px; overflow-y:scroll; height:700px;\">\r\n");
      out.write("   <div class=\"allwp\">\r\n");
      out.write("   \r\n");
      out.write("   <div>문의 페이지\r\n");
      out.write("      <div class=\"progress\" style=\"height: 1.5px; \">\r\n");
      out.write("           <div class=\"progress-bar\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"top\" style=\"-webkit-margin-before: -1em;\">\r\n");
      out.write("         <ul>\r\n");
      out.write("             <li class=\"m1\"><a>문의 하기</a></li>\r\n");
      out.write("             \r\n");
      out.write("             <li><a href=\"/sp/views/qna/myQna.jsp\">나의 문의내역</a></li>\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("         </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"top2\" style=\"-webkit-margin-before: -1.5em;\">\r\n");
      out.write("          <ul>\r\n");
      out.write("              <li>문의좀 하지마 시벌넘아</li>\r\n");
      out.write("              <li>니가 좀 알아봐</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   <table class=\"tableA\" style=\"-webkit-margin-before: -1.5em;\">\r\n");
      out.write("      <tbody >\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>\r\n");
      out.write("               <label>\r\n");
      out.write("                  <span class=\"star\">*</span> 문의유형\r\n");
      out.write("               </label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <select name=\"\" id=\"\" class=\"slt sltL\" title=\"대분류 선택\" style=\"width:180px;\">\r\n");
      out.write("               <option value=\"0\">대분류 선택</option>\r\n");
      out.write("               <option value=\"1\">회원정보</option>\r\n");
      out.write("               <option value=\"2\">이력서관리</option>\r\n");
      out.write("               <option value=\"3\">구직활동관리</option>\r\n");
      out.write("               <option value=\"4\">공고등록관리</option>\r\n");
      out.write("               <option value=\"5\">유료서비스</option>\r\n");
      out.write("               <option value=\"6\">오류/의견</option>\r\n");
      out.write("               <option value=\"7\">기타</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("                        \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th class=\"loc\">\r\n");
      out.write("               <label>\r\n");
      out.write("                  <span class=\"star\">*</span> 문의내용\r\n");
      out.write("               </label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <div class=\"txWp\">\r\n");
      out.write("               <textarea name=\"Contents\" id=\"Contents\" maxlength=\"3000\"></textarea>\r\n");
      out.write("               </div>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("                        \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>\r\n");
      out.write("               <label>\r\n");
      out.write("                  <span class=\"star\" >*</span> 이메일\r\n");
      out.write("               </label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <input type=\"text\" name=\"email\" id=\"email\" class=\"ipt\" placeholder=\"답변 받을 메일 주소를 입력해 주세요\" style=\"width:94%\" maxlength=\"50\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("                       \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th class=\"loc_1\">\r\n");
      out.write("               <label>전화번호</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <input type=\"text\" name=\"phone\" id=\"phone\" class=\"ipt\" maxlength=\"20\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </tbody>   \r\n");
      out.write("   </table>\r\n");
      out.write("   <div class=\"privacyWp\">\r\n");
      out.write("    <div class=\"privacy\">\r\n");
      out.write("    <h2>개인정보수집 및 이용안내</h2>\r\n");
      out.write("    <p><b>문의에 대한 처리 및 답변</b>을 위해 <b>이메일, 계정정보, 전화번호(선택), IP주소, 브라우저 및 OS 정보</b>가 수집되며,수집된 정보는 <b>평생 보관</b>합니다.<br>이에 동의하지 않을 경우 문의/제안 등록이 불가하며, 선택항목은 입력하지 않더라도 서비스이용에 제한을 두지 않습니다.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <p class=\"agree\">\r\n");
      out.write("       <input type=\"checkbox\" name=\"PimsAgree\" id=\"PimsAgree\" class=\"chk\" value=\"\">\r\n");
      out.write("       <label for=\"PimsAgree\">개인정보수집 및 이용안내에 동의합니다.</label>\r\n");
      out.write("    </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <p class=\"btn\">\r\n");
      out.write("       <button type=\"button\" id=\"btn_submit\" class=\"bBtn bg-dark\">보내기</button>\r\n");
      out.write("       <a href=\"javascript:self.close();\" class=\"cBtn\">취소</a>\r\n");
      out.write("    </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
