/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-07-03 09:21:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.local;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.what.semi.common.template.LocalPageInfo;
import com.what.semi.common.template.PageInfo;
import com.what.semi.recruitment.model.vo.RecruitmentVo;
import java.util.ArrayList;

public final class localSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/nav.jsp", Long.valueOf(1530014139831L));
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1530089635221L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1530007682069L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.what.semi.common.template.PageInfo");
    _jspx_imports_classes.add("com.what.semi.recruitment.model.vo.RecruitmentVo");
    _jspx_imports_classes.add("com.what.semi.common.template.LocalPageInfo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<RecruitmentVo> list = 
		(ArrayList<RecruitmentVo>)request.getAttribute("list"); 
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	int listCount = pi.getTotalCount();
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	
	int mapLevel = (Integer)request.getAttribute("mapLevel");
	
	double centerLatitude = (Double) request.getAttribute("centerLatitude");
	double centerLongitude = (Double) request.getAttribute("centerLongitude");

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String id = (String)session.getAttribute("id");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>[오늘뭐해?]홈페이지</title>\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"/sp/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/sp/vendor/bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("   <script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=154d504288d7ddddd16f6867efe451af&libraries=services,clusterer,drawing\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"/sp/css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("    <link href=\"/sp/css/daum.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"/sp/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction loadLocalList() {\r\n");
      out.write("\t\t\tlocation.href = \"/sp/localList.do\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//추후 회원의 구인게시물/이력서를 불러올 function - 회원정보를 parameter로 설정해야함\r\n");
      out.write("\t\tfunction loadMyList() {\r\n");
      out.write("\t\t\tlocation.href = \"/sp/views/member/join.jsp\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//추후 회원정보변경 페이지를 불러올 function - 회원정보를 parameter로 설정해야함\r\n");
      out.write("\t\tfunction updateMyInfo() {\r\n");
      out.write("\t\t\tlocation.href = \"/sp/views/recruitment/recruitmentForm.jsp\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"/sp/indexList.do\">오늘뭐해?</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("          ");
if(id != null){ 
      out.write("\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"/sp/views/member/join.jsp\">개인정보수정\r\n");
      out.write("                <span class=\"sr-only\">(current)</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"/sp/getResume.do\">이력서/업체정보관리</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"/sp/views/qna/qnaList.jsp\">Q&A</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\">근로내역/고용내역</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"/sp/views/member/dropMember.jsp\">회원탈퇴</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("           ");
} 
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Content -->\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"/sp/css/daumMap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <div class=\"container\" style=\"min-height: 800px\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".btn {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\n");
      out.write("\r\n");
      out.write("#loginFrm {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<!-- <script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script> -->\r\n");
      out.write("<!-- branch test -->\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction login() {\r\n");
      out.write("\t\t$(\"#loginFrm\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction join() {\r\n");
      out.write("\t\tlocation.href = \"/sp/views/member/join.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction loadLocalList() {\r\n");
      out.write("\t\tlocation.href = \"/sp/localList.do\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logout(){\r\n");
      out.write("\t\tlocation.href=\"/sp/views/member/logout.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-lg-3\">\r\n");
      out.write("<br><br>\r\n");
      out.write("<div class=\"list-group\">\r\n");
      out.write("\t");
if(id == null){ 
      out.write("\r\n");
      out.write("\t\t<form id=\"loginFrm\" action=\"/sp/login.do\" method=\"POST\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control mb-1\" name=\"id\" placeholder=\"아이디\" /> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control mb-1\" name=\"pw\" placeholder=\"비밀번호\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" size=\"15\" value=\"로그인\" class=\"btn btn-dark btn-sm btn-block\" onclick=\"login();\" /> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" size=\"15\" value=\"회원가입\" class=\"btn btn-dark btn-sm btn-block\" onclick=\"join();\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<h5 class=\"text-center\">");
      out.print(id );
      out.write("님 환영합니다</h5>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-dark btn-sm btn-block\" onclick=\"logout();\">로그아웃</button>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<div class=\"list-group\">\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-default btn-lg btn-block bg-dark\">맞춤알바</button>\r\n");
      out.write("\t\t<!-- 지역 알바로 이동 -->\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"loadLocalList();\"\r\n");
      out.write("\t\t\tclass=\"btn btn-lg btn-block bg-dark\">지역알바</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-block btn-dark\">일별알바</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-block btn-dark\">구직자정보</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        <!-- /.col-lg-3 -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- 지도API예제연습-->\r\n");
      out.write("        <div class=\"col-lg-9 my-4\">\r\n");
      out.write("          <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("             <div class=\"nowMap\">\r\n");
      out.write("            <div class=\"selArea\">\r\n");
      out.write("            <button type=\"button\" class=\"btnO\" id=\"btn_map_area\" onclick=\"map_area_move_view('')\">\r\n");
      out.write("               <span>지역 직접선택</span>\r\n");
      out.write("            </button> \r\n");
      out.write("            <!-- 레이어 열기 : btnO 적용 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("         <div id=\"dev_map_area_view\" class=\"helpLayer\" hidden=\"true\">\r\n");
      out.write("            <div class=\"popCon\">\r\n");
      out.write("                  <p class=\"title\">* 지역을 선택하시면 <strong>중심지역(시청·구청·주민센터)</strong>으로 지도가 이동합니다.</p>\r\n");
      out.write("               <ul class=\"local\">\r\n");
      out.write("                  <li id=\"dev_map_sicode_I000\"><a href=\"javascript:map_areagu_search('I000')\">서울</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_B000\"><a href=\"javascript:map_areagu_search('B000')\">경기</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_K000\"><a href=\"javascript:map_areagu_search('K000')\">인천</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_A000\"><a href=\"javascript:map_areagu_search('A000')\">강원</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_G000\"><a href=\"javascript:map_areagu_search('G000')\">대전</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_1000\"><a href=\"javascript:map_areagu_search('1000')\">세종</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_O000\"><a href=\"javascript:map_areagu_search('O000')\">충남</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_P000\"><a href=\"javascript:map_areagu_search('P000')\">충북</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_H000\"><a href=\"javascript:map_areagu_search('H000')\">부산</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_J000\"><a href=\"javascript:map_areagu_search('J000')\">울산</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_C000\"><a href=\"javascript:map_areagu_search('C000')\">경남</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_D000\"><a href=\"javascript:map_areagu_search('D000')\">경북</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_F000\"><a href=\"javascript:map_areagu_search('F000')\">대구</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_E000\"><a href=\"javascript:map_areagu_search('E000')\">광주</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_L000\"><a href=\"javascript:map_areagu_search('L000')\">전남</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_M000\"><a href=\"javascript:map_areagu_search('M000')\">전북</a></li>\r\n");
      out.write("                  <li id=\"dev_map_sicode_N000\"><a href=\"javascript:map_areagu_search('N000')\">제주</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("                  <div id=\"dev_map_areagu_box\" class=\"area\">\r\n");
      out.write("                     <h3 class=\"skip\">서울</h3>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I010\"><a href=\"javascript:map_move_gu('37.51731','127.0475','315995','546551','I010');\">강남구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I020\"><a href=\"javascript:map_move_gu('37.53013','127.1237','322750','547908','I020');\">강동구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I030\"><a href=\"javascript:map_move_gu('37.63976','127.0255','314189','560160','I030');\">강북구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I040\"><a href=\"javascript:map_move_gu('37.55093','126.8496','298549','550478','I040');\">강서구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I050\"><a href=\"javascript:map_move_gu('37.47815','126.9515','307459','542295','I050');\">관악구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I060\"><a href=\"javascript:map_move_gu('37.53862','127.0824','319101','548885','I060');\">광진구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I070\"><a href=\"javascript:map_move_gu('37.49547','126.8875','301825','544282','I070');\">구로구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I080\"><a href=\"javascript:map_move_gu('37.45708','126.8957','302497','540013','I080');\">금천구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I090\"><a href=\"javascript:map_move_gu('37.65436','127.0564','316940','561753','I090');\">노원구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I100\"><a href=\"javascript:map_move_gu('37.66877','127.0471','316135','563360','I100');\">도봉구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I110\"><a href=\"javascript:map_move_gu('37.57453','127.0396','315365','552908','I110');\">동대문구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I120\"><a href=\"javascript:map_move_gu('37.51245','126.9395','306441','546114','I120');\">동작구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I130\"><a href=\"javascript:map_move_gu('37.56632','126.9015','303151','552131','I130');\">마포구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I140\"><a href=\"javascript:map_move_gu('37.57922','126.9368','306286','553527','I140');\">서대문구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I150\"><a href=\"javascript:map_move_gu('37.48357','127.0326','314639','542820','I150');\">서초구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I160\"><a href=\"javascript:map_move_gu('37.56346','127.0368','315103','551682','I160');\">성동구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I170\"><a href=\"javascript:map_move_gu('37.58941','127.0167','313360','554580','I170');\">성북구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I180\"><a href=\"javascript:map_move_gu('37.51452','127.1062','321185','546190','I180');\">송파구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I190\"><a href=\"javascript:map_move_gu('37.51701','126.8666','300006','546695','I190');\">양천구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I200\"><a href=\"javascript:map_move_gu('37.52644','126.896','302614','547710','I200');\">영등포구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I210\"><a href=\"javascript:map_move_gu('37.53253','126.9905','310973','548292','I210');\">용산구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I220\"><a href=\"javascript:map_move_gu('37.60278','126.9291','305642','556149','I220');\">은평구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I230\"><a href=\"javascript:map_move_gu('37.57304','126.9796','310063','552798','I230');\">종로구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I240\"><a href=\"javascript:map_move_gu('37.56385','126.9976','311639','551761','I240');\">중구</a></li>\r\n");
      out.write("                        <li id=\"dev_map_gucode_I250\"><a href=\"javascript:map_move_gu('37.60633','127.0926','320075','556391','I250');\">중랑구</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               <div id=\"dev_map_areagu_box\" class=\"area\"></div>\r\n");
      out.write("               <div id=\"dev_map_areadong_box\" class=\"dong\"></div>\r\n");
      out.write("               <div class=\"btns\" id=\"gi_area_S_form\" style=\"display:none;\">\r\n");
      out.write("                  <button type=\"button\" class=\"btnSch\" onclick=\"map_move(gi_loc_lat, gi_loc_lng);$('div.partWrap ul li:first').click();map_area_move_view('0');\"><span>검색</span></button>\r\n");
      out.write("                  <button type=\"button\" class=\"btnCan\" onclick=\"map_area_move_view('0');\"><span>취소</span></button>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"popClose\">\r\n");
      out.write("               <button class=\"btn btn-dark btn-sm btn-block ml-2\" type=\"button\" onclick=\"javascript:map_area_move_view('0');\">\r\n");
      out.write("                  <span>닫기</span>\r\n");
      out.write("               </button>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("         </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("      <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("           <div id=\"map\"  style=\"width:auto;height:400px;\"></div>\r\n");
      out.write("            <p>* 원하는 위치로 지도를 움직인 후 검색을 클릭하세요. \r\n");
      out.write("                 <button class=\"btn btn-dark btn-sm btn-block ml-2\" id=\"btn1\" onclick=\"localList();\">\r\n");
      out.write("                      <span>검색</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("            </p>\r\n");
      out.write("      </div>         \r\n");
      out.write("      \r\n");
      out.write("        <!-- 지도API예제연습-->\r\n");
      out.write("         \r\n");
      out.write("           <div class=\"row\">\r\n");
      out.write("         ");
for(RecruitmentVo rv : list) {
      out.write("\r\n");
      out.write("               <div class=\"col-lg-3 col-md-3 col-sm-4 col-6 mb-4\">\r\n");
      out.write("                 <div class=\"card h-100\">\r\n");
      out.write("                   <a href=\"\"><img class=\"card-img-top\" src=\"http://placehold.it/300x300\" alt=\"\"></a>\r\n");
      out.write("                   <div class=\"card-body\">\r\n");
      out.write("                     <h4 class=\"card-title\">\r\n");
      out.write("                       <a href=\"\">");
      out.print(rv.getRecruitment_name() );
      out.write("</a><!-- 게시물 이름 -->\r\n");
      out.write("                     </h4>\r\n");
      out.write("                     <h5>시급 : ");
      out.print(rv.getPay());
      out.write("</h5>\r\n");
      out.write("                     <p class=\"card-text\">");
      out.print(rv.getRecruitment_title() );
      out.write("</p>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"card-footer\">\r\n");
      out.write("                     <small class=\"text-muted\">");
      out.print(rv.getAddress() );
      out.write("</small>\r\n");
      out.write("                   </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("               </div>\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- /.row -->\r\n");
      out.write("        <!--====================================   페이지선택버튼    ==================================  -->\r\n");
      out.write("           <div class=\"btn-toolbar mb-1\" role=\"toolbar\">\r\n");
      out.write("\t\t\t  <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t\t\t\t<button onclick=\"movePage(");
      out.print(currentPage==1?1:currentPage-1);
      out.write(");\" type=\"button\" class=\"btn btn-default bg-dark text-white\">◀</button>\r\n");
      out.write("\t\t\t\t\t");
for(int i = startPage; i <= endPage; i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
if(currentPage != i){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button onclick=\"movePage();\" type=\"button\" class=\"btn btn-default bg-dark text-white\">1</button>\r\n");
      out.write("\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default bg-dark text-white disabled\">1</button>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button onclick=\"movePage(");
      out.print(currentPage==maxPage?maxPage:maxPage+1);
      out.write(");\" type=\"button\" class=\"btn btn-default bg-dark text-white\">▶</button>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("      <!--=========================================================================================-->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.col-lg-9 -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.row -->\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=154d504288d7ddddd16f6867efe451af&libraries=services,clusterer,drawing\"></script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("            \r\n");
      out.write("   var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("   mapOption = { \r\n");
      out.write("\t   \r\n");
      out.write("\t\tcenter: new daum.maps.LatLng(");
      out.print(centerLatitude);
      out.write(',');
      out.write(' ');
      out.print(centerLongitude);
      out.write("), // 지도의 중심좌표\r\n");
      out.write("\t\tlevel: ");
      out.print(mapLevel);
      out.write(" // 지도의 확대 레벨\r\n");
      out.write("\r\n");
      out.write("   };\r\n");
      out.write("   \r\n");
      out.write("   // 지도를 생성합니다\r\n");
      out.write("   var map = new daum.maps.Map(mapContainer, mapOption); \r\n");
      out.write("   \r\n");
      out.write("   // 일반 지도와 스카이뷰로 지도 타입을 전환할 수 있는 지도타입 컨트롤을 생성합니다\r\n");
      out.write("   var mapTypeControl = new daum.maps.MapTypeControl(); \r\n");
      out.write("   \r\n");
      out.write("   // 지도 타입 컨트롤을 지도에 표시합니다\r\n");
      out.write("   // daum.maps.ControlPosition은 컨트롤이 표시될 위치를 정의하는데 TOPRIGHT는 오른쪽 위를 의미합니다\r\n");
      out.write("   map.addControl(mapTypeControl, daum.maps.ControlPosition.TOPRIGHT); \r\n");
      out.write("   \r\n");
      out.write("   // 지도에 컨트롤을 추가해야 지도위에 표시됩니다\r\n");
      out.write("    var mapTypeControl = new daum.maps.MapTypeControl(); \r\n");
      out.write("    \r\n");
      out.write("   // 지도 확대 축소를 제어할 수 있는  줌 컨트롤을 생성합니다\r\n");
      out.write("   var zoomControl = new daum.maps.ZoomControl();\r\n");
      out.write("   map.addControl(zoomControl, daum.maps.ControlPosition.RIGHT);\r\n");
      out.write("   \r\n");
      out.write("   // 마커를 표시할 위치와 title 객체 배열입니다 \r\n");
      out.write("      var positions = [\r\n");
      out.write("      ");
int count=0;
      out.write("\r\n");
      out.write("      ");
for(RecruitmentVo rv : list){
      out.write("\r\n");
      out.write("         ");
if(count==0){
      out.write("   \r\n");
      out.write("         {content: '<div onclick=\"\">");
      out.print(rv.getRecruitment_name());
      out.write("</div>', \r\n");
      out.write("         latlng: new daum.maps.LatLng(");
      out.print(rv.getR_latitude());
      out.write(',');
      out.write(' ');
      out.print(rv.getR_longitude());
      out.write(") }\r\n");
      out.write("         ");
}else{
      out.write("\r\n");
      out.write("         ,{content: '<div onclick=\"\">");
      out.print(rv.getRecruitment_name());
      out.write("</div>', \r\n");
      out.write("         latlng: new daum.maps.LatLng(");
      out.print(rv.getR_latitude());
      out.write(',');
      out.write(' ');
      out.print(rv.getR_longitude());
      out.write(") }\r\n");
      out.write("         \r\n");
      out.write("         ");
}
      out.write("\r\n");
      out.write("         ");
count++;
      out.write("\r\n");
      out.write("      ");
}
      out.write("\r\n");
      out.write("      ];\r\n");
      out.write("      console.log('배열생성');\r\n");
      out.write("   \r\n");
      out.write("   // 마커 이미지의 이미지 주소입니다\r\n");
      out.write("   var imageSrc = \"http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png\"; \r\n");
      out.write("       \r\n");
      out.write("   for (var i = 0; i < positions.length; i ++) {\r\n");
      out.write("       \r\n");
      out.write("       // 마커 이미지의 이미지 크기 입니다\r\n");
      out.write("       var imageSize = new daum.maps.Size(24, 35); \r\n");
      out.write("       \r\n");
      out.write("       // 마커 이미지를 생성합니다    \r\n");
      out.write("       var markerImage = new daum.maps.MarkerImage(imageSrc, imageSize); \r\n");
      out.write("       \r\n");
      out.write("      \r\n");
      out.write("       // 마커를 생성합니다\r\n");
      out.write("       var marker = new daum.maps.Marker({\r\n");
      out.write("           map: map, // 마커를 표시할 지도\r\n");
      out.write("           position: positions[i].latlng, // 마커를 표시할 위치\r\n");
      out.write("           image : markerImage // 마커 이미지 \r\n");
      out.write("       });\r\n");
      out.write("       \r\n");
      out.write("       // 마커에 표시할 인포윈도우를 생성합니다 \r\n");
      out.write("       var infowindow = new daum.maps.InfoWindow({\r\n");
      out.write("           content: positions[i].content // 인포윈도우에 표시할 내용\r\n");
      out.write("       });\r\n");
      out.write("       \r\n");
      out.write("       daum.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));\r\n");
      out.write("       daum.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   // 인포윈도우를 표시하는 클로저를 만드는 함수입니다 \r\n");
      out.write("   function makeOverListener(map, marker, infowindow) {\r\n");
      out.write("       return function() {\r\n");
      out.write("           infowindow.open(map, marker);\r\n");
      out.write("       };\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   // 인포윈도우를 닫는 클로저를 만드는 함수입니다 \r\n");
      out.write("   function makeOutListener(infowindow) {\r\n");
      out.write("       return function() {\r\n");
      out.write("           infowindow.close();\r\n");
      out.write("       };\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function localList() {\r\n");
      out.write("          // 지도의 현재 중심좌표를 얻어옵니다 \r\n");
      out.write("          var center = map.getCenter(); \r\n");
      out.write("          \r\n");
      out.write("          // 지도의 현재 영역을 얻어옵니다 \r\n");
      out.write("          var bounds = map.getBounds();\r\n");
      out.write("          \r\n");
      out.write("          // 영역의 남서쪽 좌표를 얻어옵니다 \r\n");
      out.write("          var swLatLng = bounds.getSouthWest(); \r\n");
      out.write("          \r\n");
      out.write("          // 영역의 북동쪽 좌표를 얻어옵니다 \r\n");
      out.write("          var neLatLng = bounds.getNorthEast(); \r\n");
      out.write("          \r\n");
      out.write("          // 영역정보를 문자열로 얻어옵니다. ((남,서), (북,동)) 형식입니다\r\n");
      out.write("          var boundsStr = bounds.toString();\r\n");
      out.write("          location.href = \"/sp/localList.do?sLatitude=\"+swLatLng.getLat()\r\n");
      out.write("                +\"&wLongitude=\"+swLatLng.getLng()\r\n");
      out.write("                +\"&nLatitude=\"+neLatLng.getLat()\r\n");
      out.write("                +\"&eLongitude=\"+neLatLng.getLng()\r\n");
      out.write("                +\"&centerLatitude=\"+center.getLat()\r\n");
      out.write("                +\"&centerLongitude=\"+center.getLng()\r\n");
      out.write("                +\"&mapLevel=\"+map.getLevel();\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("      }\r\n");
      out.write("   \r\n");
      out.write("   //지역선택 레이어 open/close\r\n");
      out.write("   function map_area_move_view(view_stat) {\r\n");
      out.write("      if(view_stat == \"1\"){   //open\r\n");
      out.write("         $(\"#dev_map_area_view\").removeClass(\"hide\");\r\n");
      out.write("         $(\"#btn_map_area\").attr(\"class\",\"btnC\");\r\n");
      out.write("      } else if(view_stat == \"0\"){ //close\r\n");
      out.write("         $(\"#dev_map_area_view\").addClass(\"hide\");\r\n");
      out.write("         $(\"#btn_map_area\").attr(\"class\",\"btnO\");\r\n");
      out.write("      } else {\r\n");
      out.write("         if($(\"#dev_map_area_view\").hasClass(\"hide\")) {\r\n");
      out.write("            $(\"#dev_map_area_view\").removeClass(\"hide\");\r\n");
      out.write("            $(\"#btn_map_area\").attr(\"class\",\"btnC\");\r\n");
      out.write("         } else {\r\n");
      out.write("            $(\"#dev_map_area_view\").addClass(\"hide\");\r\n");
      out.write("            $(\"#btn_map_area\").attr(\"class\",\"btnO\");\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //구군 선택 이동\r\n");
      out.write("   function map_move_gu(loc_lat, loc_lng, loc_x, loc_y, gu_code) {\r\n");
      out.write("      document.form.map_gu.value = gu_code;\r\n");
      out.write("\r\n");
      out.write("      $(\"#dev_map_areagu_box .on\").removeClass(\"on\");\r\n");
      out.write("      $(\"#dev_map_gucode_\"+ gu_code).addClass(\"on\");\r\n");
      out.write("      $(\"#gi_area_S_form\").show();\r\n");
      out.write("      gi_loc_lat = loc_lat;\r\n");
      out.write("      gi_loc_lng = loc_lng;\r\n");
      out.write("\r\n");
      out.write("      //map_move(loc_x, loc_y);\r\n");
      out.write("      map_areadong_search(gu_code);\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //지역선택 레이어 close/open\r\n");
      out.write("   function map_area_move_view(view_stat) {\r\n");
      out.write("      if(view_stat == \"1\"){   //open\r\n");
      out.write("         $(\"#dev_map_area_view\").removeClass(\"hide\");\r\n");
      out.write("         $(\"#btn_map_area\").attr(\"class\",\"btnC\");\r\n");
      out.write("      } else if(view_stat == \"0\"){ //close\r\n");
      out.write("         $(\"#dev_map_area_view\").addClass(\"hide\");\r\n");
      out.write("         $(\"#btn_map_area\").attr(\"class\",\"btnO\");\r\n");
      out.write("      } else {\r\n");
      out.write("         if($(\"#dev_map_area_view\").hasClass(\"hide\")) {\r\n");
      out.write("            $(\"#dev_map_area_view\").removeClass(\"hide\");\r\n");
      out.write("            $(\"#btn_map_area\").attr(\"class\",\"btnC\");\r\n");
      out.write("         } else {\r\n");
      out.write("            $(\"#dev_map_area_view\").addClass(\"hide\");\r\n");
      out.write("            $(\"#btn_map_area\").attr(\"class\",\"btnO\");\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   // 동 선택 이동\r\n");
      out.write("   function map_move_dong(loc_lat, loc_lng, loc_x, loc_y, dong_code) {\r\n");
      out.write("      document.form.map_dong.value = dong_code;\r\n");
      out.write("\r\n");
      out.write("      $(\"#dev_map_areadong_box .on\").removeClass(\"on\");\r\n");
      out.write("      $(\"#dev_map_dongcode_\"+ dong_code).addClass(\"on\");\r\n");
      out.write("\r\n");
      out.write("      gi_loc_lat = loc_lat;\r\n");
      out.write("      gi_loc_lng = loc_lng;\r\n");
      out.write("\r\n");
      out.write("      //map_move(loc_x, loc_y);\r\n");
      out.write("      //map_area_move_view('0');\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //구군 검색\r\n");
      out.write("   function map_areagu_search(gval) {\r\n");
      out.write("      $(\"#dev_map_areadong_box\").html(\"\").addClass(\"hide\");\r\n");
      out.write("      $(\".local .on\").removeClass(\"on\");\r\n");
      out.write("      $(\"#dev_map_sicode_\"+ gval).addClass(\"on\");\r\n");
      out.write("\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url:\"/list/gi/mon_search_form_data.asp?sch_type=maparea&scd=\"+ gval +\"&gcd=\"+ document.form.map_gu.value ,\r\n");
      out.write("         success:function(response, status, request){\r\n");
      out.write("         //   alert(\"aa code=\"+request.status+\", message=\"+request.responseText)\r\n");
      out.write("            if(response != \"\"){\r\n");
      out.write("               $(\"#dev_map_areagu_box\").html(response).removeClass(\"hide\");\r\n");
      out.write("            }\r\n");
      out.write("         },\r\n");
      out.write("         error:function (request,status,error){\r\n");
      out.write("         //   alert(\"bb code=\"+request.status+\", message=\"+request.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("      $(\"#gi_area_S_form\").hide();\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //동 검색\r\n");
      out.write("   function map_areadong_search(gval) {\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url:\"/list/gi/mon_search_form_data.asp?sch_type=mapareadong&gcd=\"+ gval +\"&dcd=\"+ document.form.map_dong.value ,\r\n");
      out.write("         success:function(response, status, request){\r\n");
      out.write("         //   alert(\"aa code=\"+request.status+\", message=\"+request.responseText)\r\n");
      out.write("            if(response != \"\"){\r\n");
      out.write("               $(\"#dev_map_areadong_box\").html(response).removeClass(\"hide\");\r\n");
      out.write("            }\r\n");
      out.write("         },\r\n");
      out.write("         error:function (request,status,error){\r\n");
      out.write("         //   alert(\"bb code=\"+request.status+\", message=\"+request.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("      $(\"#gi_area_S_form\").show();\r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"py-5 bg-dark\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2017</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.container -->\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript -->\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"/sp/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
